### ISSUE TITLE
Merging Flask-BabelEx back into Flask-Babel

### ISSUE THREAD

**Issue by ThiefMaster** [mrjoes/flask-babelex#20]
After some discussions in the Pallets discord (where people, including myself, actually assumed that BabelEx is dead due to not having had a release in the last 4 years), I'm wondering whether it wouldn't make sense to merge back the changes from Flask-BabelEx into Flask-Babel.

As the lead developer of a [project](https://github.com/indico/indico) that currently uses Flask-BabelEx and the extra features it has, I'd love to see that happen (since actively maintained libs are nicer to work with, and for something as "core" as i18n having one single lib would make things more straightforward for anyone).

We can actually dedicate some developer time for this, but it would be interesting to hear your opinion on that as well, @mrjoes, since you started the fork in the first place.

**Comment by mrjoes** [comment]
I am totally fine merging into the flask-babel. Originally this fork started as a merge request against baseline flask-babel, but Armin decided to not merge it for some reason and I don't remember what it was back then.

Anyway, if flask-babel maintainer(s) are willing to merge dynamic transaction domains into the mainline repo - I can definitely deprecate the fork and switch flask-admin to use flask-babel.

**Comment by ThiefMaster** [comment]
@mitsuhiko do you remember the reason for not merging the changes upstream?

**Comment by mitsuhiko** [comment]
I don't have a recollection of anything.

**Comment by mrjoes** [comment]
Done.

**Comment by mrjoes** [comment]
Sorry, closed by an accident.

**Comment by ThiefMaster** [comment]
We just created a PR for it; a review from you would be appreciated! (also, in case it didn't ping you, there's a question for you in the PR's description)

**Comment by TkTech** [comment]
This is now live with version 2.0.
